version: "3.9"
   
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_django
    image: app_django
    restart: unless-stopped
    volumes:
      - ./..:/app
    ports:
      - "8000:8000"